[package]
name = "bevy_tilemap_types"
version = "0.1.0"
authors = ["Joshua J. Bouw <dev@joshuajbouw.com>"]
edition = "2018"
description = "Common types used across Bevy Tilemaps"
repository = "https://github.com/joshuajbouw/bevy_tilemap"
license = "MIT"
keywords = ["bevy", "bevy_tilemap"]
documentation = "https://docs.rs/bevy_tilemap/latest/bevy_tilemap_types/"

[package.metadata.docs.rs]
features = ["serialize"]
default-target = "x86_64-pc-windows-msvc"

[features]
serialize = ["serde"]

[dependencies]
bevy_math = "0.4"
bevy_render = "0.4"
serde = { version = "1.0", optional = true, features = ["derive"] }
