[package]
name = "rapier"
version = "0.1.0"
authors = ["Joshua J. Bouw <dev@joshuajbouw.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
